import "../gtk-types/gtk-3.0-ambient";
import "../gtk-types/gdk-3.0-ambient";
import "../gtk-types/cairo-1.0-ambient";
import "../gtk-types/gnomebluetooth-3.0-ambient";
import "../gtk-types/dbusmenugtk3-0.4-ambient";
import "../gtk-types/gobject-2.0-ambient";
import "../gtk-types/nm-1.0-ambient";
import "../gtk-types/soup-3.0-ambient";
import "../gtk-types/gvc-1.0-ambient";
import type GObjectTypes from "../../types/gtk-types/gobject-2.0";
import Gtk from 'gi://Gtk?version=3.0';
import type GtkTypes from "../../types/gtk-types/gtk-3.0";
export type Command = string | ((...args: unknown[]) => boolean);
export interface BaseProps<Self> {
    className?: string;
    classNames?: string[];
    style?: string;
    css?: string;
    halign?: 'fill' | 'start' | 'end' | 'center' | 'baseline';
    valign?: 'fill' | 'start' | 'end' | 'center' | 'baseline';
    connections?: ([
        string,
        (self: Self, ...args: unknown[]) => unknown
    ] | [
        number,
        (self: Self, ...args: unknown[]) => unknown
    ] | [
        GObjectTypes.Object,
        (self: Self, ...args: unknown[]) => unknown,
        string
    ])[];
    properties?: [prop: string, value: unknown][];
    binds?: [
        prop: string,
        obj: GObjectTypes.Object,
        objProp?: string,
        transform?: (value: unknown) => unknown
    ][];
    setup?: (self: Self) => void;
}
export default function <T extends typeof Gtk.Widget, Props>(W: T, GTypeName?: string): {
    new (params?: (BaseProps<T> & Props) | any): {
        toggleClassName(className: string, condition?: boolean): void;
        halign: string;
        valign: string;
        class_name: string;
        class_names: string[];
        setCss(css: string): void;
        setStyle(css: string): void;
        style: string;
        css: string;
        child: GtkTypes.Widget | null;
        readonly parent: GtkTypes.Container | null;
        app_paintable: boolean;
        can_default: boolean;
        can_focus: boolean;
        readonly composite_child: boolean;
        double_buffered: boolean;
        events: import("../../types/gtk-types/gdk-3.0").Gdk.EventMask;
        expand: boolean;
        focus_on_click: boolean;
        has_default: boolean;
        has_focus: boolean;
        has_tooltip: boolean;
        height_request: number;
        hexpand: boolean;
        hexpand_set: boolean;
        is_focus: boolean;
        margin: number;
        margin_bottom: number;
        margin_end: number;
        margin_left: number;
        margin_right: number;
        margin_start: number;
        margin_top: number;
        name: string | null;
        no_show_all: boolean;
        opacity: number;
        receives_default: boolean;
        readonly scale_factor: number;
        sensitive: boolean;
        tooltip_markup: string | null;
        tooltip_text: string | null;
        vexpand: boolean;
        vexpand_set: boolean;
        visible: boolean;
        width_request: number;
        readonly window: import("../../types/gtk-types/gdk-3.0").Gdk.Window;
        parent_instance: GObjectTypes.InitiallyUnowned;
        activate(): boolean;
        add_accelerator(accel_signal: string | null, accel_group: GtkTypes.AccelGroup, accel_key: number, accel_mods: import("../../types/gtk-types/gdk-3.0").Gdk.ModifierType, accel_flags: GtkTypes.AccelFlags): void;
        add_device_events(device: import("../../types/gtk-types/gdk-3.0").Gdk.Device, events: import("../../types/gtk-types/gdk-3.0").Gdk.EventMask): void;
        add_events(events: number): void;
        add_mnemonic_label(label: GtkTypes.Widget): void;
        add_tick_callback(callback: GtkTypes.TickCallback): number;
        can_activate_accel(signal_id: number): boolean;
        child_focus(direction: GtkTypes.DirectionType): boolean;
        child_notify(child_property: string | null): void;
        class_path(): [number, string | null, string | null];
        compute_expand(orientation: GtkTypes.Orientation): boolean;
        create_pango_context(): import("../../types/gtk-types/pango-1.0").Pango.Context;
        create_pango_layout(text: string | null): import("../../types/gtk-types/pango-1.0").Pango.Layout;
        destroy(): void;
        destroyed(widget_pointer: GtkTypes.Widget): GtkTypes.Widget;
        device_is_shadowed(device: import("../../types/gtk-types/gdk-3.0").Gdk.Device): boolean;
        drag_begin(targets: GtkTypes.TargetList, actions: import("../../types/gtk-types/gdk-3.0").Gdk.DragAction, button: number, event: import("../../types/gtk-types/gdk-3.0").Gdk.Event | null): import("../../types/gtk-types/gdk-3.0").Gdk.DragContext;
        drag_begin_with_coordinates(targets: GtkTypes.TargetList, actions: import("../../types/gtk-types/gdk-3.0").Gdk.DragAction, button: number, event: import("../../types/gtk-types/gdk-3.0").Gdk.Event | null, x: number, y: number): import("../../types/gtk-types/gdk-3.0").Gdk.DragContext;
        drag_check_threshold(start_x: number, start_y: number, current_x: number, current_y: number): boolean;
        drag_dest_add_image_targets(): void;
        drag_dest_add_text_targets(): void;
        drag_dest_add_uri_targets(): void;
        drag_dest_find_target(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, target_list: GtkTypes.TargetList | null): import("../../types/gtk-types/gdk-3.0").Gdk.Atom;
        drag_dest_get_target_list(): GtkTypes.TargetList | null;
        drag_dest_get_track_motion(): boolean;
        drag_dest_set(flags: GtkTypes.DestDefaults, targets: GtkTypes.TargetEntry[] | null, actions: import("../../types/gtk-types/gdk-3.0").Gdk.DragAction): void;
        drag_dest_set_proxy(proxy_window: import("../../types/gtk-types/gdk-3.0").Gdk.Window, protocol: import("../../types/gtk-types/gdk-3.0").Gdk.DragProtocol, use_coordinates: boolean): void;
        drag_dest_set_target_list(target_list: GtkTypes.TargetList | null): void;
        drag_dest_set_track_motion(track_motion: boolean): void;
        drag_dest_unset(): void;
        drag_get_data(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, target: import("../../types/gtk-types/gdk-3.0").Gdk.Atom, time_: number): void;
        drag_highlight(): void;
        drag_source_add_image_targets(): void;
        drag_source_add_text_targets(): void;
        drag_source_add_uri_targets(): void;
        drag_source_get_target_list(): GtkTypes.TargetList | null;
        drag_source_set(start_button_mask: import("../../types/gtk-types/gdk-3.0").Gdk.ModifierType, targets: GtkTypes.TargetEntry[] | null, actions: import("../../types/gtk-types/gdk-3.0").Gdk.DragAction): void;
        drag_source_set_icon_gicon(icon: import("../../types/gtk-types/gio-2.0").Gio.Icon): void;
        drag_source_set_icon_name(icon_name: string | null): void;
        drag_source_set_icon_pixbuf(pixbuf: import("../../types/gtk-types/gdkpixbuf-2.0").GdkPixbuf.Pixbuf): void;
        drag_source_set_icon_stock(stock_id: string | null): void;
        drag_source_set_target_list(target_list: GtkTypes.TargetList | null): void;
        drag_source_unset(): void;
        drag_unhighlight(): void;
        draw(cr: import("../../types/gtk-types/cairo-1.0").cairo.Context): void;
        ensure_style(): void;
        error_bell(): void;
        event(event: import("../../types/gtk-types/gdk-3.0").Gdk.Event): boolean;
        freeze_child_notify(): void;
        get_accessible(): import("../../types/gtk-types/atk-1.0").Atk.Object;
        get_action_group(prefix: string | null): import("../../types/gtk-types/gio-2.0").Gio.ActionGroup | null;
        get_allocated_baseline(): number;
        get_allocated_height(): number;
        get_allocated_size(): [import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle, number];
        get_allocated_width(): number;
        get_allocation(): import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle;
        get_ancestor(widget_type: GObjectTypes.GType<unknown>): GtkTypes.Widget | null;
        get_app_paintable(): boolean;
        get_can_default(): boolean;
        get_can_focus(): boolean;
        get_child_requisition(): GtkTypes.Requisition;
        get_child_visible(): boolean;
        get_clip(): import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle;
        get_clipboard(selection: import("../../types/gtk-types/gdk-3.0").Gdk.Atom): GtkTypes.Clipboard;
        get_composite_name(): string | null;
        get_device_enabled(device: import("../../types/gtk-types/gdk-3.0").Gdk.Device): boolean;
        get_device_events(device: import("../../types/gtk-types/gdk-3.0").Gdk.Device): import("../../types/gtk-types/gdk-3.0").Gdk.EventMask;
        get_direction(): GtkTypes.TextDirection;
        get_display(): import("../../types/gtk-types/gdk-3.0").Gdk.Display;
        get_double_buffered(): boolean;
        get_events(): number;
        get_focus_on_click(): boolean;
        get_font_map(): import("../../types/gtk-types/pango-1.0").Pango.FontMap | null;
        get_font_options(): import("../../types/gtk-types/cairo-1.0").cairo.FontOptions | null;
        get_frame_clock(): import("../../types/gtk-types/gdk-3.0").Gdk.FrameClock | null;
        get_halign(): GtkTypes.Align;
        get_has_tooltip(): boolean;
        get_has_window(): boolean;
        get_hexpand(): boolean;
        get_hexpand_set(): boolean;
        get_mapped(): boolean;
        get_margin_bottom(): number;
        get_margin_end(): number;
        get_margin_left(): number;
        get_margin_right(): number;
        get_margin_start(): number;
        get_margin_top(): number;
        get_modifier_mask(intent: import("../../types/gtk-types/gdk-3.0").Gdk.ModifierIntent): import("../../types/gtk-types/gdk-3.0").Gdk.ModifierType;
        get_modifier_style(): GtkTypes.RcStyle;
        get_name(): string | null;
        get_no_show_all(): boolean;
        get_opacity(): number;
        get_pango_context(): import("../../types/gtk-types/pango-1.0").Pango.Context;
        get_parent(): GtkTypes.Widget | null;
        get_parent_window(): import("../../types/gtk-types/gdk-3.0").Gdk.Window | null;
        get_path(): GtkTypes.WidgetPath;
        get_pointer(): [number, number];
        get_preferred_height(): [number, number];
        get_preferred_height_and_baseline_for_width(width: number): [number, number, number, number];
        get_preferred_height_for_width(width: number): [number, number];
        get_preferred_size(): [GtkTypes.Requisition, GtkTypes.Requisition];
        get_preferred_width(): [number, number];
        get_preferred_width_for_height(height: number): [number, number];
        get_realized(): boolean;
        get_receives_default(): boolean;
        get_request_mode(): GtkTypes.SizeRequestMode;
        get_requisition(): GtkTypes.Requisition;
        get_root_window(): import("../../types/gtk-types/gdk-3.0").Gdk.Window;
        get_scale_factor(): number;
        get_screen(): import("../../types/gtk-types/gdk-3.0").Gdk.Screen;
        get_sensitive(): boolean;
        get_settings(): GtkTypes.Settings;
        get_size_request(): [number, number];
        get_state(): GtkTypes.StateType;
        get_state_flags(): GtkTypes.StateFlags;
        get_style(): GtkTypes.Style;
        get_style_context(): GtkTypes.StyleContext;
        get_support_multidevice(): boolean;
        get_template_child(widget_type: GObjectTypes.GType<unknown>, name: string | null): GObjectTypes.Object;
        get_tooltip_markup(): string | null;
        get_tooltip_text(): string | null;
        get_tooltip_window(): GtkTypes.Window;
        get_toplevel(): GtkTypes.Widget;
        get_valign(): GtkTypes.Align;
        get_valign_with_baseline(): GtkTypes.Align;
        get_vexpand(): boolean;
        get_vexpand_set(): boolean;
        get_visible(): boolean;
        get_visual(): import("../../types/gtk-types/gdk-3.0").Gdk.Visual;
        get_window(): import("../../types/gtk-types/gdk-3.0").Gdk.Window | null;
        grab_add(): void;
        grab_default(): void;
        grab_focus(): void;
        grab_remove(): void;
        has_grab(): boolean;
        has_rc_style(): boolean;
        has_screen(): boolean;
        has_visible_focus(): boolean;
        hide(): void;
        hide_on_delete(): boolean;
        in_destruction(): boolean;
        init_template(): void;
        input_shape_combine_region(region: import("../../types/gtk-types/cairo-1.0").cairo.Region | null): void;
        insert_action_group(name: string | null, group: import("../../types/gtk-types/gio-2.0").Gio.ActionGroup | null): void;
        intersect(area: import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle): [boolean, import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle];
        is_ancestor(ancestor: GtkTypes.Widget): boolean;
        is_composited(): boolean;
        is_drawable(): boolean;
        is_sensitive(): boolean;
        is_toplevel(): boolean;
        is_visible(): boolean;
        keynav_failed(direction: GtkTypes.DirectionType): boolean;
        list_accel_closures(): GObjectTypes.TClosure<any, any>[];
        list_action_prefixes(): string[];
        list_mnemonic_labels(): GtkTypes.Widget[];
        map(): void;
        mnemonic_activate(group_cycling: boolean): boolean;
        modify_base(state: GtkTypes.StateType, color: import("../../types/gtk-types/gdk-3.0").Gdk.Color | null): void;
        modify_bg(state: GtkTypes.StateType, color: import("../../types/gtk-types/gdk-3.0").Gdk.Color | null): void;
        modify_cursor(primary: import("../../types/gtk-types/gdk-3.0").Gdk.Color | null, secondary: import("../../types/gtk-types/gdk-3.0").Gdk.Color | null): void;
        modify_fg(state: GtkTypes.StateType, color: import("../../types/gtk-types/gdk-3.0").Gdk.Color | null): void;
        modify_font(font_desc: import("../../types/gtk-types/pango-1.0").Pango.FontDescription | null): void;
        modify_style(style: GtkTypes.RcStyle): void;
        modify_text(state: GtkTypes.StateType, color: import("../../types/gtk-types/gdk-3.0").Gdk.Color | null): void;
        override_background_color(state: GtkTypes.StateFlags, color: import("../../types/gtk-types/gdk-3.0").Gdk.RGBA | null): void;
        override_color(state: GtkTypes.StateFlags, color: import("../../types/gtk-types/gdk-3.0").Gdk.RGBA | null): void;
        override_cursor(cursor: import("../../types/gtk-types/gdk-3.0").Gdk.RGBA | null, secondary_cursor: import("../../types/gtk-types/gdk-3.0").Gdk.RGBA | null): void;
        override_font(font_desc: import("../../types/gtk-types/pango-1.0").Pango.FontDescription | null): void;
        override_symbolic_color(name: string | null, color: import("../../types/gtk-types/gdk-3.0").Gdk.RGBA | null): void;
        path(): [number, string | null, string | null];
        queue_allocate(): void;
        queue_compute_expand(): void;
        queue_draw(): void;
        queue_draw_area(x: number, y: number, width: number, height: number): void;
        queue_draw_region(region: import("../../types/gtk-types/cairo-1.0").cairo.Region): void;
        queue_resize(): void;
        queue_resize_no_redraw(): void;
        realize(): void;
        region_intersect(region: import("../../types/gtk-types/cairo-1.0").cairo.Region): import("../../types/gtk-types/cairo-1.0").cairo.Region;
        register_window(window: import("../../types/gtk-types/gdk-3.0").Gdk.Window): void;
        remove_accelerator(accel_group: GtkTypes.AccelGroup, accel_key: number, accel_mods: import("../../types/gtk-types/gdk-3.0").Gdk.ModifierType): boolean;
        remove_mnemonic_label(label: GtkTypes.Widget): void;
        remove_tick_callback(id: number): void;
        render_icon(stock_id: string | null, size: number, detail: string | null): import("../../types/gtk-types/gdkpixbuf-2.0").GdkPixbuf.Pixbuf | null;
        render_icon_pixbuf(stock_id: string | null, size: number): import("../../types/gtk-types/gdkpixbuf-2.0").GdkPixbuf.Pixbuf | null;
        reparent(new_parent: GtkTypes.Widget): void;
        reset_rc_styles(): void;
        reset_style(): void;
        send_expose(event: import("../../types/gtk-types/gdk-3.0").Gdk.Event): number;
        send_focus_change(event: import("../../types/gtk-types/gdk-3.0").Gdk.Event): boolean;
        set_accel_path(accel_path: string | null, accel_group: GtkTypes.AccelGroup | null): void;
        set_allocation(allocation: import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle): void;
        set_app_paintable(app_paintable: boolean): void;
        set_can_default(can_default: boolean): void;
        set_can_focus(can_focus: boolean): void;
        set_child_visible(is_visible: boolean): void;
        set_clip(clip: import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle): void;
        set_composite_name(name: string | null): void;
        set_device_enabled(device: import("../../types/gtk-types/gdk-3.0").Gdk.Device, enabled: boolean): void;
        set_device_events(device: import("../../types/gtk-types/gdk-3.0").Gdk.Device, events: import("../../types/gtk-types/gdk-3.0").Gdk.EventMask): void;
        set_direction(dir: GtkTypes.TextDirection): void;
        set_double_buffered(double_buffered: boolean): void;
        set_events(events: number): void;
        set_focus_on_click(focus_on_click: boolean): void;
        set_font_map(font_map: import("../../types/gtk-types/pango-1.0").Pango.FontMap | null): void;
        set_font_options(options: import("../../types/gtk-types/cairo-1.0").cairo.FontOptions | null): void;
        set_halign(align: GtkTypes.Align): void;
        set_has_tooltip(has_tooltip: boolean): void;
        set_has_window(has_window: boolean): void;
        set_hexpand(expand: boolean): void;
        set_hexpand_set(set: boolean): void;
        set_mapped(mapped: boolean): void;
        set_margin_bottom(margin: number): void;
        set_margin_end(margin: number): void;
        set_margin_left(margin: number): void;
        set_margin_right(margin: number): void;
        set_margin_start(margin: number): void;
        set_margin_top(margin: number): void;
        set_name(name: string | null): void;
        set_no_show_all(no_show_all: boolean): void;
        set_opacity(opacity: number): void;
        set_parent(parent: GtkTypes.Widget): void;
        set_parent_window(parent_window: import("../../types/gtk-types/gdk-3.0").Gdk.Window): void;
        set_realized(realized: boolean): void;
        set_receives_default(receives_default: boolean): void;
        set_redraw_on_allocate(redraw_on_allocate: boolean): void;
        set_sensitive(sensitive: boolean): void;
        set_size_request(width: number, height: number): void;
        set_state(state: GtkTypes.StateType): void;
        set_state_flags(flags: GtkTypes.StateFlags, clear: boolean): void;
        set_style(style: GtkTypes.Style | null): void;
        set_support_multidevice(support_multidevice: boolean): void;
        set_tooltip_markup(markup: string | null): void;
        set_tooltip_text(text: string | null): void;
        set_tooltip_window(custom_window: GtkTypes.Window | null): void;
        set_valign(align: GtkTypes.Align): void;
        set_vexpand(expand: boolean): void;
        set_vexpand_set(set: boolean): void;
        set_visible(visible: boolean): void;
        set_visual(visual: import("../../types/gtk-types/gdk-3.0").Gdk.Visual | null): void;
        set_window(window: import("../../types/gtk-types/gdk-3.0").Gdk.Window): void;
        shape_combine_region(region: import("../../types/gtk-types/cairo-1.0").cairo.Region | null): void;
        show(): void;
        show_all(): void;
        show_now(): void;
        size_allocate(allocation: import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle): void;
        size_allocate_with_baseline(allocation: import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle, baseline: number): void;
        size_request(): GtkTypes.Requisition;
        style_attach(): void;
        style_get_property(property_name: string | null, value: any): void;
        thaw_child_notify(): void;
        translate_coordinates(dest_widget: GtkTypes.Widget, src_x: number, src_y: number): [boolean, number, number];
        trigger_tooltip_query(): void;
        unmap(): void;
        unparent(): void;
        unrealize(): void;
        unregister_window(window: import("../../types/gtk-types/gdk-3.0").Gdk.Window): void;
        unset_state_flags(flags: GtkTypes.StateFlags): void;
        vfunc_adjust_baseline_allocation(baseline: number): void;
        vfunc_adjust_baseline_request(minimum_baseline: number, natural_baseline: number): void;
        vfunc_adjust_size_allocation(orientation: GtkTypes.Orientation, minimum_size: number, natural_size: number, allocated_pos: number, allocated_size: number): void;
        vfunc_adjust_size_request(orientation: GtkTypes.Orientation, minimum_size: number, natural_size: number): void;
        vfunc_button_press_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventButton): boolean;
        vfunc_button_release_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventButton): boolean;
        vfunc_can_activate_accel(signal_id: number): boolean;
        vfunc_child_notify(child_property: GObjectTypes.ParamSpec): void;
        vfunc_composited_changed(): void;
        vfunc_compute_expand(hexpand_p: boolean, vexpand_p: boolean): void;
        vfunc_configure_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventConfigure): boolean;
        vfunc_damage_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventExpose): boolean;
        vfunc_delete_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventAny): boolean;
        vfunc_destroy(): void;
        vfunc_destroy_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventAny): boolean;
        vfunc_direction_changed(previous_direction: GtkTypes.TextDirection): void;
        vfunc_dispatch_child_properties_changed(n_pspecs: number, pspecs: GObjectTypes.ParamSpec): void;
        vfunc_drag_begin(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext): void;
        vfunc_drag_data_delete(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext): void;
        vfunc_drag_data_get(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, selection_data: GtkTypes.SelectionData, info: number, time_: number): void;
        vfunc_drag_data_received(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, x: number, y: number, selection_data: GtkTypes.SelectionData, info: number, time_: number): void;
        vfunc_drag_drop(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, x: number, y: number, time_: number): boolean;
        vfunc_drag_end(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext): void;
        vfunc_drag_failed(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, result: GtkTypes.DragResult): boolean;
        vfunc_drag_leave(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, time_: number): void;
        vfunc_drag_motion(context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, x: number, y: number, time_: number): boolean;
        vfunc_draw(cr: import("../../types/gtk-types/cairo-1.0").cairo.Context): boolean;
        vfunc_enter_notify_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventCrossing): boolean;
        vfunc_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.Event): boolean;
        vfunc_focus(direction: GtkTypes.DirectionType): boolean;
        vfunc_focus_in_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventFocus): boolean;
        vfunc_focus_out_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventFocus): boolean;
        vfunc_get_accessible(): import("../../types/gtk-types/atk-1.0").Atk.Object;
        vfunc_get_preferred_height(): [number, number];
        vfunc_get_preferred_height_and_baseline_for_width(width: number): [number, number, number, number];
        vfunc_get_preferred_height_for_width(width: number): [number, number];
        vfunc_get_preferred_width(): [number, number];
        vfunc_get_preferred_width_for_height(height: number): [number, number];
        vfunc_get_request_mode(): GtkTypes.SizeRequestMode;
        vfunc_grab_broken_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventGrabBroken): boolean;
        vfunc_grab_focus(): void;
        vfunc_grab_notify(was_grabbed: boolean): void;
        vfunc_hide(): void;
        vfunc_hierarchy_changed(previous_toplevel: GtkTypes.Widget): void;
        vfunc_key_press_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventKey): boolean;
        vfunc_key_release_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventKey): boolean;
        vfunc_keynav_failed(direction: GtkTypes.DirectionType): boolean;
        vfunc_leave_notify_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventCrossing): boolean;
        vfunc_map(): void;
        vfunc_map_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventAny): boolean;
        vfunc_mnemonic_activate(group_cycling: boolean): boolean;
        vfunc_motion_notify_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventMotion): boolean;
        vfunc_move_focus(direction: GtkTypes.DirectionType): void;
        vfunc_parent_set(previous_parent: GtkTypes.Widget): void;
        vfunc_popup_menu(): boolean;
        vfunc_property_notify_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventProperty): boolean;
        vfunc_proximity_in_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventProximity): boolean;
        vfunc_proximity_out_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventProximity): boolean;
        vfunc_query_tooltip(x: number, y: number, keyboard_tooltip: boolean, tooltip: GtkTypes.Tooltip): boolean;
        vfunc_queue_draw_region(region: import("../../types/gtk-types/cairo-1.0").cairo.Region): void;
        vfunc_realize(): void;
        vfunc_screen_changed(previous_screen: import("../../types/gtk-types/gdk-3.0").Gdk.Screen): void;
        vfunc_scroll_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventScroll): boolean;
        vfunc_selection_clear_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventSelection): boolean;
        vfunc_selection_get(selection_data: GtkTypes.SelectionData, info: number, time_: number): void;
        vfunc_selection_notify_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventSelection): boolean;
        vfunc_selection_received(selection_data: GtkTypes.SelectionData, time_: number): void;
        vfunc_selection_request_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventSelection): boolean;
        vfunc_show(): void;
        vfunc_show_all(): void;
        vfunc_show_help(help_type: GtkTypes.WidgetHelpType): boolean;
        vfunc_size_allocate(allocation: import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle): void;
        vfunc_state_changed(previous_state: GtkTypes.StateType): void;
        vfunc_state_flags_changed(previous_state_flags: GtkTypes.StateFlags): void;
        vfunc_style_set(previous_style: GtkTypes.Style): void;
        vfunc_style_updated(): void;
        vfunc_touch_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventTouch): boolean;
        vfunc_unmap(): void;
        vfunc_unmap_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventAny): boolean;
        vfunc_unrealize(): void;
        vfunc_visibility_notify_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventVisibility): boolean;
        vfunc_window_state_event(event: import("../../types/gtk-types/gdk-3.0").Gdk.EventWindowState): boolean;
        connect(sigName: "accel-closures-changed", callback: GtkTypes.Widget.AccelClosuresChangedSignalCallback): number;
        connect(sigName: "button-press-event", callback: GtkTypes.Widget.ButtonPressEventSignalCallback): number;
        connect(sigName: "button-release-event", callback: GtkTypes.Widget.ButtonReleaseEventSignalCallback): number;
        connect(sigName: "can-activate-accel", callback: GtkTypes.Widget.CanActivateAccelSignalCallback): number;
        connect(sigName: "child-notify", callback: GtkTypes.Widget.ChildNotifySignalCallback): number;
        connect(sigName: "composited-changed", callback: GtkTypes.Widget.CompositedChangedSignalCallback): number;
        connect(sigName: "configure-event", callback: GtkTypes.Widget.ConfigureEventSignalCallback): number;
        connect(sigName: "damage-event", callback: GtkTypes.Widget.DamageEventSignalCallback): number;
        connect(sigName: "delete-event", callback: GtkTypes.Widget.DeleteEventSignalCallback): number;
        connect(sigName: "destroy", callback: GtkTypes.Widget.DestroySignalCallback): number;
        connect(sigName: "destroy-event", callback: GtkTypes.Widget.DestroyEventSignalCallback): number;
        connect(sigName: "direction-changed", callback: GtkTypes.Widget.DirectionChangedSignalCallback): number;
        connect(sigName: "drag-begin", callback: GtkTypes.Widget.DragBeginSignalCallback): number;
        connect(sigName: "drag-data-delete", callback: GtkTypes.Widget.DragDataDeleteSignalCallback): number;
        connect(sigName: "drag-data-get", callback: GtkTypes.Widget.DragDataGetSignalCallback): number;
        connect(sigName: "drag-data-received", callback: GtkTypes.Widget.DragDataReceivedSignalCallback): number;
        connect(sigName: "drag-drop", callback: GtkTypes.Widget.DragDropSignalCallback): number;
        connect(sigName: "drag-end", callback: GtkTypes.Widget.DragEndSignalCallback): number;
        connect(sigName: "drag-failed", callback: GtkTypes.Widget.DragFailedSignalCallback): number;
        connect(sigName: "drag-leave", callback: GtkTypes.Widget.DragLeaveSignalCallback): number;
        connect(sigName: "drag-motion", callback: GtkTypes.Widget.DragMotionSignalCallback): number;
        connect(sigName: "draw", callback: GtkTypes.Widget.DrawSignalCallback): number;
        connect(sigName: "enter-notify-event", callback: GtkTypes.Widget.EnterNotifyEventSignalCallback): number;
        connect(sigName: "event", callback: GtkTypes.Widget.EventSignalCallback): number;
        connect(sigName: "event-after", callback: GtkTypes.Widget.EventAfterSignalCallback): number;
        connect(sigName: "focus", callback: GtkTypes.Widget.FocusSignalCallback): number;
        connect(sigName: "focus-in-event", callback: GtkTypes.Widget.FocusInEventSignalCallback): number;
        connect(sigName: "focus-out-event", callback: GtkTypes.Widget.FocusOutEventSignalCallback): number;
        connect(sigName: "grab-broken-event", callback: GtkTypes.Widget.GrabBrokenEventSignalCallback): number;
        connect(sigName: "grab-focus", callback: GtkTypes.Widget.GrabFocusSignalCallback): number;
        connect(sigName: "grab-notify", callback: GtkTypes.Widget.GrabNotifySignalCallback): number;
        connect(sigName: "hide", callback: GtkTypes.Widget.HideSignalCallback): number;
        connect(sigName: "hierarchy-changed", callback: GtkTypes.Widget.HierarchyChangedSignalCallback): number;
        connect(sigName: "key-press-event", callback: GtkTypes.Widget.KeyPressEventSignalCallback): number;
        connect(sigName: "key-release-event", callback: GtkTypes.Widget.KeyReleaseEventSignalCallback): number;
        connect(sigName: "keynav-failed", callback: GtkTypes.Widget.KeynavFailedSignalCallback): number;
        connect(sigName: "leave-notify-event", callback: GtkTypes.Widget.LeaveNotifyEventSignalCallback): number;
        connect(sigName: "map", callback: GtkTypes.Widget.MapSignalCallback): number;
        connect(sigName: "map-event", callback: GtkTypes.Widget.MapEventSignalCallback): number;
        connect(sigName: "mnemonic-activate", callback: GtkTypes.Widget.MnemonicActivateSignalCallback): number;
        connect(sigName: "motion-notify-event", callback: GtkTypes.Widget.MotionNotifyEventSignalCallback): number;
        connect(sigName: "move-focus", callback: GtkTypes.Widget.MoveFocusSignalCallback): number;
        connect(sigName: "parent-set", callback: GtkTypes.Widget.ParentSetSignalCallback): number;
        connect(sigName: "popup-menu", callback: GtkTypes.Widget.PopupMenuSignalCallback): number;
        connect(sigName: "property-notify-event", callback: GtkTypes.Widget.PropertyNotifyEventSignalCallback): number;
        connect(sigName: "proximity-in-event", callback: GtkTypes.Widget.ProximityInEventSignalCallback): number;
        connect(sigName: "proximity-out-event", callback: GtkTypes.Widget.ProximityOutEventSignalCallback): number;
        connect(sigName: "query-tooltip", callback: GtkTypes.Widget.QueryTooltipSignalCallback): number;
        connect(sigName: "realize", callback: GtkTypes.Widget.RealizeSignalCallback): number;
        connect(sigName: "screen-changed", callback: GtkTypes.Widget.ScreenChangedSignalCallback): number;
        connect(sigName: "scroll-event", callback: GtkTypes.Widget.ScrollEventSignalCallback): number;
        connect(sigName: "selection-clear-event", callback: GtkTypes.Widget.SelectionClearEventSignalCallback): number;
        connect(sigName: "selection-get", callback: GtkTypes.Widget.SelectionGetSignalCallback): number;
        connect(sigName: "selection-notify-event", callback: GtkTypes.Widget.SelectionNotifyEventSignalCallback): number;
        connect(sigName: "selection-received", callback: GtkTypes.Widget.SelectionReceivedSignalCallback): number;
        connect(sigName: "selection-request-event", callback: GtkTypes.Widget.SelectionRequestEventSignalCallback): number;
        connect(sigName: "show", callback: GtkTypes.Widget.ShowSignalCallback): number;
        connect(sigName: "show-help", callback: GtkTypes.Widget.ShowHelpSignalCallback): number;
        connect(sigName: "size-allocate", callback: GtkTypes.Widget.SizeAllocateSignalCallback): number;
        connect(sigName: "state-changed", callback: GtkTypes.Widget.StateChangedSignalCallback): number;
        connect(sigName: "state-flags-changed", callback: GtkTypes.Widget.StateFlagsChangedSignalCallback): number;
        connect(sigName: "style-set", callback: GtkTypes.Widget.StyleSetSignalCallback): number;
        connect(sigName: "style-updated", callback: GtkTypes.Widget.StyleUpdatedSignalCallback): number;
        connect(sigName: "touch-event", callback: GtkTypes.Widget.TouchEventSignalCallback): number;
        connect(sigName: "unmap", callback: GtkTypes.Widget.UnmapSignalCallback): number;
        connect(sigName: "unmap-event", callback: GtkTypes.Widget.UnmapEventSignalCallback): number;
        connect(sigName: "unrealize", callback: GtkTypes.Widget.UnrealizeSignalCallback): number;
        connect(sigName: "visibility-notify-event", callback: GtkTypes.Widget.VisibilityNotifyEventSignalCallback): number;
        connect(sigName: "window-state-event", callback: GtkTypes.Widget.WindowStateEventSignalCallback): number;
        connect(sigName: "notify::app-paintable", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::can-default", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::can-focus", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::composite-child", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::double-buffered", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::events", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::expand", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::focus-on-click", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::halign", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::has-default", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::has-focus", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::has-tooltip", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::height-request", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::hexpand", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::hexpand-set", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::is-focus", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::margin", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::margin-bottom", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::margin-end", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::margin-left", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::margin-right", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::margin-start", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::margin-top", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::name", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::no-show-all", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::opacity", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::parent", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::receives-default", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::scale-factor", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::sensitive", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::style", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::tooltip-markup", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::tooltip-text", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::valign", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::vexpand", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::vexpand-set", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::visible", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::width-request", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: "notify::window", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect(sigName: string, callback: (...args: any[]) => void): number;
        connect_after(sigName: "accel-closures-changed", callback: GtkTypes.Widget.AccelClosuresChangedSignalCallback): number;
        connect_after(sigName: "button-press-event", callback: GtkTypes.Widget.ButtonPressEventSignalCallback): number;
        connect_after(sigName: "button-release-event", callback: GtkTypes.Widget.ButtonReleaseEventSignalCallback): number;
        connect_after(sigName: "can-activate-accel", callback: GtkTypes.Widget.CanActivateAccelSignalCallback): number;
        connect_after(sigName: "child-notify", callback: GtkTypes.Widget.ChildNotifySignalCallback): number;
        connect_after(sigName: "composited-changed", callback: GtkTypes.Widget.CompositedChangedSignalCallback): number;
        connect_after(sigName: "configure-event", callback: GtkTypes.Widget.ConfigureEventSignalCallback): number;
        connect_after(sigName: "damage-event", callback: GtkTypes.Widget.DamageEventSignalCallback): number;
        connect_after(sigName: "delete-event", callback: GtkTypes.Widget.DeleteEventSignalCallback): number;
        connect_after(sigName: "destroy", callback: GtkTypes.Widget.DestroySignalCallback): number;
        connect_after(sigName: "destroy-event", callback: GtkTypes.Widget.DestroyEventSignalCallback): number;
        connect_after(sigName: "direction-changed", callback: GtkTypes.Widget.DirectionChangedSignalCallback): number;
        connect_after(sigName: "drag-begin", callback: GtkTypes.Widget.DragBeginSignalCallback): number;
        connect_after(sigName: "drag-data-delete", callback: GtkTypes.Widget.DragDataDeleteSignalCallback): number;
        connect_after(sigName: "drag-data-get", callback: GtkTypes.Widget.DragDataGetSignalCallback): number;
        connect_after(sigName: "drag-data-received", callback: GtkTypes.Widget.DragDataReceivedSignalCallback): number;
        connect_after(sigName: "drag-drop", callback: GtkTypes.Widget.DragDropSignalCallback): number;
        connect_after(sigName: "drag-end", callback: GtkTypes.Widget.DragEndSignalCallback): number;
        connect_after(sigName: "drag-failed", callback: GtkTypes.Widget.DragFailedSignalCallback): number;
        connect_after(sigName: "drag-leave", callback: GtkTypes.Widget.DragLeaveSignalCallback): number;
        connect_after(sigName: "drag-motion", callback: GtkTypes.Widget.DragMotionSignalCallback): number;
        connect_after(sigName: "draw", callback: GtkTypes.Widget.DrawSignalCallback): number;
        connect_after(sigName: "enter-notify-event", callback: GtkTypes.Widget.EnterNotifyEventSignalCallback): number;
        connect_after(sigName: "event", callback: GtkTypes.Widget.EventSignalCallback): number;
        connect_after(sigName: "event-after", callback: GtkTypes.Widget.EventAfterSignalCallback): number;
        connect_after(sigName: "focus", callback: GtkTypes.Widget.FocusSignalCallback): number;
        connect_after(sigName: "focus-in-event", callback: GtkTypes.Widget.FocusInEventSignalCallback): number;
        connect_after(sigName: "focus-out-event", callback: GtkTypes.Widget.FocusOutEventSignalCallback): number;
        connect_after(sigName: "grab-broken-event", callback: GtkTypes.Widget.GrabBrokenEventSignalCallback): number;
        connect_after(sigName: "grab-focus", callback: GtkTypes.Widget.GrabFocusSignalCallback): number;
        connect_after(sigName: "grab-notify", callback: GtkTypes.Widget.GrabNotifySignalCallback): number;
        connect_after(sigName: "hide", callback: GtkTypes.Widget.HideSignalCallback): number;
        connect_after(sigName: "hierarchy-changed", callback: GtkTypes.Widget.HierarchyChangedSignalCallback): number;
        connect_after(sigName: "key-press-event", callback: GtkTypes.Widget.KeyPressEventSignalCallback): number;
        connect_after(sigName: "key-release-event", callback: GtkTypes.Widget.KeyReleaseEventSignalCallback): number;
        connect_after(sigName: "keynav-failed", callback: GtkTypes.Widget.KeynavFailedSignalCallback): number;
        connect_after(sigName: "leave-notify-event", callback: GtkTypes.Widget.LeaveNotifyEventSignalCallback): number;
        connect_after(sigName: "map", callback: GtkTypes.Widget.MapSignalCallback): number;
        connect_after(sigName: "map-event", callback: GtkTypes.Widget.MapEventSignalCallback): number;
        connect_after(sigName: "mnemonic-activate", callback: GtkTypes.Widget.MnemonicActivateSignalCallback): number;
        connect_after(sigName: "motion-notify-event", callback: GtkTypes.Widget.MotionNotifyEventSignalCallback): number;
        connect_after(sigName: "move-focus", callback: GtkTypes.Widget.MoveFocusSignalCallback): number;
        connect_after(sigName: "parent-set", callback: GtkTypes.Widget.ParentSetSignalCallback): number;
        connect_after(sigName: "popup-menu", callback: GtkTypes.Widget.PopupMenuSignalCallback): number;
        connect_after(sigName: "property-notify-event", callback: GtkTypes.Widget.PropertyNotifyEventSignalCallback): number;
        connect_after(sigName: "proximity-in-event", callback: GtkTypes.Widget.ProximityInEventSignalCallback): number;
        connect_after(sigName: "proximity-out-event", callback: GtkTypes.Widget.ProximityOutEventSignalCallback): number;
        connect_after(sigName: "query-tooltip", callback: GtkTypes.Widget.QueryTooltipSignalCallback): number;
        connect_after(sigName: "realize", callback: GtkTypes.Widget.RealizeSignalCallback): number;
        connect_after(sigName: "screen-changed", callback: GtkTypes.Widget.ScreenChangedSignalCallback): number;
        connect_after(sigName: "scroll-event", callback: GtkTypes.Widget.ScrollEventSignalCallback): number;
        connect_after(sigName: "selection-clear-event", callback: GtkTypes.Widget.SelectionClearEventSignalCallback): number;
        connect_after(sigName: "selection-get", callback: GtkTypes.Widget.SelectionGetSignalCallback): number;
        connect_after(sigName: "selection-notify-event", callback: GtkTypes.Widget.SelectionNotifyEventSignalCallback): number;
        connect_after(sigName: "selection-received", callback: GtkTypes.Widget.SelectionReceivedSignalCallback): number;
        connect_after(sigName: "selection-request-event", callback: GtkTypes.Widget.SelectionRequestEventSignalCallback): number;
        connect_after(sigName: "show", callback: GtkTypes.Widget.ShowSignalCallback): number;
        connect_after(sigName: "show-help", callback: GtkTypes.Widget.ShowHelpSignalCallback): number;
        connect_after(sigName: "size-allocate", callback: GtkTypes.Widget.SizeAllocateSignalCallback): number;
        connect_after(sigName: "state-changed", callback: GtkTypes.Widget.StateChangedSignalCallback): number;
        connect_after(sigName: "state-flags-changed", callback: GtkTypes.Widget.StateFlagsChangedSignalCallback): number;
        connect_after(sigName: "style-set", callback: GtkTypes.Widget.StyleSetSignalCallback): number;
        connect_after(sigName: "style-updated", callback: GtkTypes.Widget.StyleUpdatedSignalCallback): number;
        connect_after(sigName: "touch-event", callback: GtkTypes.Widget.TouchEventSignalCallback): number;
        connect_after(sigName: "unmap", callback: GtkTypes.Widget.UnmapSignalCallback): number;
        connect_after(sigName: "unmap-event", callback: GtkTypes.Widget.UnmapEventSignalCallback): number;
        connect_after(sigName: "unrealize", callback: GtkTypes.Widget.UnrealizeSignalCallback): number;
        connect_after(sigName: "visibility-notify-event", callback: GtkTypes.Widget.VisibilityNotifyEventSignalCallback): number;
        connect_after(sigName: "window-state-event", callback: GtkTypes.Widget.WindowStateEventSignalCallback): number;
        connect_after(sigName: "notify::app-paintable", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::can-default", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::can-focus", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::composite-child", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::double-buffered", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::events", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::expand", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::focus-on-click", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::halign", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::has-default", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::has-focus", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::has-tooltip", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::height-request", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::hexpand", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::hexpand-set", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::is-focus", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::margin", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::margin-bottom", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::margin-end", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::margin-left", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::margin-right", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::margin-start", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::margin-top", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::name", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::no-show-all", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::opacity", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::parent", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::receives-default", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::scale-factor", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::sensitive", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::style", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::tooltip-markup", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::tooltip-text", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::valign", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::vexpand", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::vexpand-set", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::visible", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::width-request", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: "notify::window", callback: ($obj: GtkTypes.Widget, pspec: GObjectTypes.ParamSpec) => void): number;
        connect_after(sigName: string, callback: (...args: any[]) => void): number;
        emit(sigName: "accel-closures-changed", ...args: any[]): void;
        emit(sigName: "button-press-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventButton, ...args: any[]): void;
        emit(sigName: "button-release-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventButton, ...args: any[]): void;
        emit(sigName: "can-activate-accel", signal_id: number, ...args: any[]): void;
        emit(sigName: "child-notify", child_property: GObjectTypes.ParamSpec, ...args: any[]): void;
        emit(sigName: "composited-changed", ...args: any[]): void;
        emit(sigName: "configure-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventConfigure, ...args: any[]): void;
        emit(sigName: "damage-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventExpose, ...args: any[]): void;
        emit(sigName: "delete-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.Event, ...args: any[]): void;
        emit(sigName: "destroy", ...args: any[]): void;
        emit(sigName: "destroy-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.Event, ...args: any[]): void;
        emit(sigName: "direction-changed", previous_direction: GtkTypes.TextDirection, ...args: any[]): void;
        emit(sigName: "drag-begin", context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, ...args: any[]): void;
        emit(sigName: "drag-data-delete", context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, ...args: any[]): void;
        emit(sigName: "drag-data-get", context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, data: GtkTypes.SelectionData, info: number, time: number, ...args: any[]): void;
        emit(sigName: "drag-data-received", context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, x: number, y: number, data: GtkTypes.SelectionData, info: number, time: number, ...args: any[]): void;
        emit(sigName: "drag-drop", context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, x: number, y: number, time: number, ...args: any[]): void;
        emit(sigName: "drag-end", context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, ...args: any[]): void;
        emit(sigName: "drag-failed", context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, result: GtkTypes.DragResult, ...args: any[]): void;
        emit(sigName: "drag-leave", context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, time: number, ...args: any[]): void;
        emit(sigName: "drag-motion", context: import("../../types/gtk-types/gdk-3.0").Gdk.DragContext, x: number, y: number, time: number, ...args: any[]): void;
        emit(sigName: "draw", cr: import("../../types/gtk-types/cairo-1.0").cairo.Context, ...args: any[]): void;
        emit(sigName: "enter-notify-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventCrossing, ...args: any[]): void;
        emit(sigName: "event", event: import("../../types/gtk-types/gdk-3.0").Gdk.Event, ...args: any[]): void;
        emit(sigName: "event-after", event: import("../../types/gtk-types/gdk-3.0").Gdk.Event, ...args: any[]): void;
        emit(sigName: "focus", direction: GtkTypes.DirectionType, ...args: any[]): void;
        emit(sigName: "focus-in-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventFocus, ...args: any[]): void;
        emit(sigName: "focus-out-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventFocus, ...args: any[]): void;
        emit(sigName: "grab-broken-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventGrabBroken, ...args: any[]): void;
        emit(sigName: "grab-focus", ...args: any[]): void;
        emit(sigName: "grab-notify", was_grabbed: boolean, ...args: any[]): void;
        emit(sigName: "hide", ...args: any[]): void;
        emit(sigName: "hierarchy-changed", previous_toplevel: GtkTypes.Widget | null, ...args: any[]): void;
        emit(sigName: "key-press-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventKey, ...args: any[]): void;
        emit(sigName: "key-release-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventKey, ...args: any[]): void;
        emit(sigName: "keynav-failed", direction: GtkTypes.DirectionType, ...args: any[]): void;
        emit(sigName: "leave-notify-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventCrossing, ...args: any[]): void;
        emit(sigName: "map", ...args: any[]): void;
        emit(sigName: "map-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventAny, ...args: any[]): void;
        emit(sigName: "mnemonic-activate", group_cycling: boolean, ...args: any[]): void;
        emit(sigName: "motion-notify-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventMotion, ...args: any[]): void;
        emit(sigName: "move-focus", direction: GtkTypes.DirectionType, ...args: any[]): void;
        emit(sigName: "parent-set", old_parent: GtkTypes.Widget | null, ...args: any[]): void;
        emit(sigName: "popup-menu", ...args: any[]): void;
        emit(sigName: "property-notify-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventProperty, ...args: any[]): void;
        emit(sigName: "proximity-in-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventProximity, ...args: any[]): void;
        emit(sigName: "proximity-out-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventProximity, ...args: any[]): void;
        emit(sigName: "query-tooltip", x: number, y: number, keyboard_mode: boolean, tooltip: GtkTypes.Tooltip, ...args: any[]): void;
        emit(sigName: "realize", ...args: any[]): void;
        emit(sigName: "screen-changed", previous_screen: import("../../types/gtk-types/gdk-3.0").Gdk.Screen | null, ...args: any[]): void;
        emit(sigName: "scroll-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventScroll, ...args: any[]): void;
        emit(sigName: "selection-clear-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventSelection, ...args: any[]): void;
        emit(sigName: "selection-get", data: GtkTypes.SelectionData, info: number, time: number, ...args: any[]): void;
        emit(sigName: "selection-notify-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventSelection, ...args: any[]): void;
        emit(sigName: "selection-received", data: GtkTypes.SelectionData, time: number, ...args: any[]): void;
        emit(sigName: "selection-request-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventSelection, ...args: any[]): void;
        emit(sigName: "show", ...args: any[]): void;
        emit(sigName: "show-help", help_type: GtkTypes.WidgetHelpType, ...args: any[]): void;
        emit(sigName: "size-allocate", allocation: import("../../types/gtk-types/gdk-3.0").Gdk.Rectangle, ...args: any[]): void;
        emit(sigName: "state-changed", state: GtkTypes.StateType, ...args: any[]): void;
        emit(sigName: "state-flags-changed", flags: GtkTypes.StateFlags, ...args: any[]): void;
        emit(sigName: "style-set", previous_style: GtkTypes.Style | null, ...args: any[]): void;
        emit(sigName: "style-updated", ...args: any[]): void;
        emit(sigName: "touch-event", object: import("../../types/gtk-types/gdk-3.0").Gdk.Event, ...args: any[]): void;
        emit(sigName: "unmap", ...args: any[]): void;
        emit(sigName: "unmap-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventAny, ...args: any[]): void;
        emit(sigName: "unrealize", ...args: any[]): void;
        emit(sigName: "visibility-notify-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventVisibility, ...args: any[]): void;
        emit(sigName: "window-state-event", event: import("../../types/gtk-types/gdk-3.0").Gdk.EventWindowState, ...args: any[]): void;
        emit(sigName: "notify::app-paintable", ...args: any[]): void;
        emit(sigName: "notify::can-default", ...args: any[]): void;
        emit(sigName: "notify::can-focus", ...args: any[]): void;
        emit(sigName: "notify::composite-child", ...args: any[]): void;
        emit(sigName: "notify::double-buffered", ...args: any[]): void;
        emit(sigName: "notify::events", ...args: any[]): void;
        emit(sigName: "notify::expand", ...args: any[]): void;
        emit(sigName: "notify::focus-on-click", ...args: any[]): void;
        emit(sigName: "notify::halign", ...args: any[]): void;
        emit(sigName: "notify::has-default", ...args: any[]): void;
        emit(sigName: "notify::has-focus", ...args: any[]): void;
        emit(sigName: "notify::has-tooltip", ...args: any[]): void;
        emit(sigName: "notify::height-request", ...args: any[]): void;
        emit(sigName: "notify::hexpand", ...args: any[]): void;
        emit(sigName: "notify::hexpand-set", ...args: any[]): void;
        emit(sigName: "notify::is-focus", ...args: any[]): void;
        emit(sigName: "notify::margin", ...args: any[]): void;
        emit(sigName: "notify::margin-bottom", ...args: any[]): void;
        emit(sigName: "notify::margin-end", ...args: any[]): void;
        emit(sigName: "notify::margin-left", ...args: any[]): void;
        emit(sigName: "notify::margin-right", ...args: any[]): void;
        emit(sigName: "notify::margin-start", ...args: any[]): void;
        emit(sigName: "notify::margin-top", ...args: any[]): void;
        emit(sigName: "notify::name", ...args: any[]): void;
        emit(sigName: "notify::no-show-all", ...args: any[]): void;
        emit(sigName: "notify::opacity", ...args: any[]): void;
        emit(sigName: "notify::parent", ...args: any[]): void;
        emit(sigName: "notify::receives-default", ...args: any[]): void;
        emit(sigName: "notify::scale-factor", ...args: any[]): void;
        emit(sigName: "notify::sensitive", ...args: any[]): void;
        emit(sigName: "notify::style", ...args: any[]): void;
        emit(sigName: "notify::tooltip-markup", ...args: any[]): void;
        emit(sigName: "notify::tooltip-text", ...args: any[]): void;
        emit(sigName: "notify::valign", ...args: any[]): void;
        emit(sigName: "notify::vexpand", ...args: any[]): void;
        emit(sigName: "notify::vexpand-set", ...args: any[]): void;
        emit(sigName: "notify::visible", ...args: any[]): void;
        emit(sigName: "notify::width-request", ...args: any[]): void;
        emit(sigName: "notify::window", ...args: any[]): void;
        emit(sigName: string, ...args: any[]): void;
        disconnect(id: number): void;
        _init(config?: GtkTypes.Widget.ConstructorProperties | undefined): void;
        g_type_instance: GObjectTypes.TypeInstance;
        bind_property(source_property: string | null, target: GObjectTypes.Object, target_property: string | null, flags: GObjectTypes.BindingFlags): GObjectTypes.Binding;
        bind_property_full(source_property: string | null, target: GObjectTypes.Object, target_property: string | null, flags: GObjectTypes.BindingFlags, transform_to: GObjectTypes.TClosure<any, any>, transform_from: GObjectTypes.TClosure<any, any>): GObjectTypes.Binding;
        force_floating(): void;
        freeze_notify(): void;
        get_data(key: string | null): any;
        get_property(property_name: string | null, value: any): void;
        get_qdata(quark: number): any;
        getv(names: string[], values: any[]): void;
        is_floating(): boolean;
        notify(property_name: string | null): void;
        notify_by_pspec(pspec: GObjectTypes.ParamSpec): void;
        ref(): GObjectTypes.Object;
        ref_sink(): GObjectTypes.Object;
        run_dispose(): void;
        set_data(key: string | null, data: any): void;
        set_property(property_name: string | null, value: any): void;
        steal_data(key: string | null): any;
        steal_qdata(quark: number): any;
        thaw_notify(): void;
        unref(): void;
        watch_closure(closure: GObjectTypes.TClosure<any, any>): void;
        vfunc_constructed(): void;
        vfunc_dispatch_properties_changed(n_pspecs: number, pspecs: GObjectTypes.ParamSpec): void;
        vfunc_dispose(): void;
        vfunc_finalize(): void;
        vfunc_get_property(property_id: number, value: any, pspec: GObjectTypes.ParamSpec): void;
        vfunc_notify(pspec: GObjectTypes.ParamSpec): void;
        vfunc_set_property(property_id: number, value: any, pspec: GObjectTypes.ParamSpec): void;
        add_child(builder: GtkTypes.Builder, child: GObjectTypes.Object, type: string | null): void;
        construct_child(builder: GtkTypes.Builder, name: string | null): GObjectTypes.Object;
        custom_finished(builder: GtkTypes.Builder, child: GObjectTypes.Object | null, tagname: string | null, data: any): void;
        custom_tag_end(builder: GtkTypes.Builder, child: GObjectTypes.Object | null, tagname: string | null, data: any): void;
        custom_tag_start(builder: GtkTypes.Builder, child: GObjectTypes.Object | null, tagname: string | null): [boolean, import("../../types/gtk-types/glib-2.0").GLib.MarkupParser, any];
        get_internal_child(builder: GtkTypes.Builder, childname: string | null): GObjectTypes.Object;
        parser_finished(builder: GtkTypes.Builder): void;
        set_buildable_property(builder: GtkTypes.Builder, name: string | null, value: any): void;
        vfunc_add_child(builder: GtkTypes.Builder, child: GObjectTypes.Object, type: string | null): void;
        vfunc_construct_child(builder: GtkTypes.Builder, name: string | null): GObjectTypes.Object;
        vfunc_custom_finished(builder: GtkTypes.Builder, child: GObjectTypes.Object | null, tagname: string | null, data: any): void;
        vfunc_custom_tag_end(builder: GtkTypes.Builder, child: GObjectTypes.Object | null, tagname: string | null, data: any): void;
        vfunc_custom_tag_start(builder: GtkTypes.Builder, child: GObjectTypes.Object | null, tagname: string | null): [boolean, import("../../types/gtk-types/glib-2.0").GLib.MarkupParser, any];
        vfunc_get_internal_child(builder: GtkTypes.Builder, childname: string | null): GObjectTypes.Object;
        vfunc_get_name(): string | null;
        vfunc_parser_finished(builder: GtkTypes.Builder): void;
        vfunc_set_buildable_property(builder: GtkTypes.Builder, name: string | null, value: any): void;
        vfunc_set_name(name: string | null): void;
    };
    name: string;
    $gtype: GObjectTypes.GType<GtkTypes.Widget>;
    get_default_direction(): GtkTypes.TextDirection;
    get_default_style(): GtkTypes.Style;
    pop_composite_child(): void;
    push_composite_child(): void;
    set_default_direction(dir: GtkTypes.TextDirection): void;
    bind_template_callback_full(widget_class: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, callback_name: string | null, callback_symbol: GObjectTypes.Callback): void;
    bind_template_child_full(widget_class: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, name: string | null, internal_child: boolean, struct_offset: number): void;
    find_style_property(klass: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, property_name: string | null): GObjectTypes.ParamSpec;
    get_css_name(widget_class: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget): string | null;
    install_style_property(klass: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, pspec: GObjectTypes.ParamSpec): void;
    list_style_properties(klass: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget): GObjectTypes.ParamSpec[];
    set_accessible_role(widget_class: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, role: import("../../types/gtk-types/atk-1.0").Atk.Role): void;
    set_accessible_type(widget_class: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, type: GObjectTypes.GType<unknown>): void;
    set_connect_func(widget_class: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, connect_func: GtkTypes.BuilderConnectFunc): void;
    set_css_name(widget_class: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, name: string | null): void;
    set_template(widget_class: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, template_bytes: import("../../types/gtk-types/glib-2.0").GLib.Bytes): void;
    set_template_from_resource(widget_class: Function | GObjectTypes.GType<unknown> | GtkTypes.Widget, resource_name: string | null): void;
    newv(object_type: GObjectTypes.GType<unknown>, parameters: GObjectTypes.Parameter[]): GObjectTypes.Object;
    compat_control(what: number, data: any): number;
    interface_find_property(g_iface: GObjectTypes.TypeInterface, property_name: string | null): GObjectTypes.ParamSpec;
    interface_install_property(g_iface: GObjectTypes.TypeInterface, pspec: GObjectTypes.ParamSpec): void;
    interface_list_properties(g_iface: GObjectTypes.TypeInterface): GObjectTypes.ParamSpec[];
} & T;
