import Service from './service/service.js';
import Applications from './service/applications.js';
import Audio from './service/audio.js';
import Battery from './service/battery.js';
import Bluetooth from './service/bluetooth.js';
import Hyprland from './service/hyprland.js';
import Mpris from './service/mpris.js';
import Network from './service/network.js';
import Notifications from './service/notifications.js';
import SystemTray from './service/systemtray.js';
export { Applications, Audio, Battery, Bluetooth, Hyprland, Mpris, Network, Notifications, SystemTray, Service, };
export default Service;
