import "./gtk-types/gtk-3.0-ambient";
import "./gtk-types/gdk-3.0-ambient";
import "./gtk-types/cairo-1.0-ambient";
import "./gtk-types/gnomebluetooth-3.0-ambient";
import "./gtk-types/dbusmenugtk3-0.4-ambient";
import "./gtk-types/gobject-2.0-ambient";
import "./gtk-types/nm-1.0-ambient";
import "./gtk-types/soup-3.0-ambient";
import "./gtk-types/gvc-1.0-ambient";
import Service from './service/service.js';
import Applications from './service/applications.js';
import Audio from './service/audio.js';
import Battery from './service/battery.js';
import Bluetooth from './service/bluetooth.js';
import Hyprland from './service/hyprland.js';
import Mpris from './service/mpris.js';
import Network from './service/network.js';
import Notifications from './service/notifications.js';
import SystemTray from './service/systemtray.js';
export { Applications, Audio, Battery, Bluetooth, Hyprland, Mpris, Network, Notifications, SystemTray, Service, };
export default Service;
