[book]
authors = ["aylur"]
language = "en"
multilingual = false
src = "src"
title = "ags documentation"


[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/Aylur/ags"

[output.html.playground]
runnable = false
