name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: lint and typecheck
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - run: npm ci
    - run: npm test
